import {IDS,IDLE,BOUNDS,makeMotion,ranges} from './sim-core.mjs';
const $=x=>document.getElementById(x),s=window.studio,names={'6':'左臂 / L · 6','7':'左臂 / L · 7','8':'左臂 / L · 8','14':'右臂 / R · 14','15':'右臂 / R · 15','16':'右臂 / R · 16',pitch:'头部 / Head · PWM1',yaw:'头部 / Head · PWM2'};
let busy=false,abort=null,generation=0,applyingPlan=false;
for(const k of IDS){let row=document.createElement('tr');row.innerHTML=`<td>${names[k]}<br><small>${k==='pitch'||k==='yaw'?'μs':'raw'}</small></td><td id="live-${k}"></td><td><input id="edit-${k}" type="number" min="${BOUNDS[k][0]}" max="${BOUNDS[k][1]}" step="1" aria-label="${names[k]}目标值"><output id="range-${k}"></output></td>`;$('joint-rows').append(row);}
const sliders=$('servo-sliders');
for(const k of IDS){const label=document.createElement('label');label.className='servo-card servo-'+k;label.innerHTML=`<span>${k==='pitch'?'PWM 1':k==='yaw'?'PWM 2':'ID: '+k}</span><input type="range" min="${BOUNDS[k][0]}" max="${BOUNDS[k][1]}" step="1" id="slide-${k}" aria-label="${names[k]} slider"><output id="slide-value-${k}"></output>`;sliders.append(label);$('slide-'+k).oninput=()=>{$('edit-'+k).value=$('slide-'+k).value;$('slide-value-'+k).textContent=$('slide-'+k).value;};$('edit-'+k).addEventListener('input',()=>{$('slide-'+k).value=$('edit-'+k).value;$('slide-value-'+k).textContent=$('edit-'+k).value;});}
let selected=0;
function frameTable(a){$('frames').replaceChildren();let table=document.createElement('table');table.className='frame-table';let head=document.createElement('thead');head.innerHTML='<tr><th>帧 / #</th><th>时间 / Time</th><th>运动 / Move</th>'+IDS.map(k=>`<th>${k}</th>`).join('')+'<th>动作 / Motion</th></tr>';table.append(head);let body=document.createElement('tbody');a.frames.forEach((f,i)=>{let row=document.createElement('tr');row.dataset.frame=i;for(const text of [i+1,f.start.toFixed(2),f.move.toFixed(2),...IDS.map(k=>f.target[k]??IDLE[k]),s.label(f.label)]){let cell=document.createElement('td');cell.textContent=text;row.append(cell);}row.onclick=()=>{s.seek(f.start);loadFrame(a,i);};body.append(row);});table.append(body);$('frames').append(table);$('library-count').textContent=s.library.actions.length;}
function loadFrame(a,i){selected=i;let f=a.frames[i];IDS.forEach(k=>{$('edit-'+k).value=f.target[k]??IDLE[k];$('slide-'+k).value=$('edit-'+k).value;$('slide-value-'+k).textContent=$('edit-'+k).value;});$('move-time').value=f.move;$('hold-time').value=+(f.duration-f.move).toFixed(3);document.querySelectorAll('[data-frame]').forEach(r=>r.classList.toggle('selected',Number(r.dataset.frame)===i));let r=ranges({...a,initial:{...IDLE,...a.initial},frames:a.frames.map(f=>({...f,target:{...IDLE,...f.target}}))});IDS.forEach(k=>$('range-'+k).textContent=`Range ${r[k][0]}–${r[k][1]}`);}
function refresh(){frameTable(s.current);loadFrame(s.current,0);}window.addEventListener('studio-action',refresh);refresh();
let lastIndex=-1;function update(){let state=s.state;IDS.forEach(k=>$('live-'+k).textContent=Math.round(state.pose[k]));if(state.playing){let index=s.sample(s.current,state.time).index;if(index!==lastIndex){lastIndex=index;loadFrame(s.current,index);}}requestAnimationFrame(update);}requestAnimationFrame(update);
$('time').addEventListener('input',()=>loadFrame(s.current,s.sample(s.current,s.state.time).index));
function commit(append){try{s.seek(s.state.time);const p=Object.fromEntries(IDS.map(k=>[k,Number($('edit-'+k).value)])),f={pose:p,move_s:Number($('move-time').value),hold_s:Number($('hold-time').value),label:append?'追加姿势':'手动修改'};let steps=s.current.frames.map(v=>({pose:Object.fromEntries(IDS.map(k=>[k,v.target[k]??IDLE[k]])),move_s:v.move,hold_s:Math.max(0,v.duration-v.move),label:v.label}));if(append)steps.push(f);else steps[selected]=f;let a=makeMotion(s.current.name+' · 编辑',steps,Object.fromEntries(IDS.map(k=>[k,s.current.initial[k]??IDLE[k]])));s.addAction(a);$('status').textContent='修改已保存 / Copy saved';}catch(e){$('status').textContent=e.message;}}
$('apply-frame').onclick=()=>commit(false);$('append-frame').onclick=()=>commit(true);
$('save-motion').onclick=()=>{let blob=new Blob([JSON.stringify({schema:'xiaoji-sim-motion/v1',mode:'simulation_only',hardware_executed:false,action:s.current},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='carrot-goose-motion.json';a.click();URL.revokeObjectURL(url);};
const local=['127.0.0.1','localhost'].includes(location.hostname);
const online=/^(www\.)?(?:carrotduck|carrotgoose)\.online$/.test(location.hostname),uid=()=>local?'local':localStorage.getItem('carrotduck_user_id'),token=()=>local?'local':localStorage.getItem('carrotduck_session_token');
function connection(){const ready=(local||online)&&uid()&&token();$('connection').textContent=ready?(local?'本地 / Local':'已登录 / Signed in'):online?'请登录 / Sign in':'本地编辑 / Local';$('generate').disabled=busy||!ready;$('online-link').textContent=online?'鸭鸭 / Carrot Duck':'在线版 / Online';if(online){$('online-link').href='https://carrotduck.online/';}$('account-button').hidden=!online||!!(uid()&&token());return ready;}connection();
function cancel(reason='已取消 / Cancelled'){generation++;abort?.abort();abort=null;busy=false;$('cancel-plan').disabled=true;connection();$('plan-result').textContent=reason;}
$('cancel-plan').onclick=()=>cancel();$('reset').addEventListener('click',()=>{if(busy)cancel();});window.addEventListener('storage',e=>{if(['carrotduck_user_id','carrotduck_session_token'].includes(e.key)){cancel('账号已变更 / Account changed');s.seek(0);connection();}});
$('generate').onclick=async()=>{if(!connection())return;const prompt=$('instruction').value.trim();if(!prompt)return;let user=uid(),session=token(),epoch=++generation;abort=new AbortController();busy=true;connection();$('cancel-plan').disabled=false;$('plan-result').textContent='生成中 / Planning…';const timeout=setTimeout(()=>abort?.abort(),65000);try{const context={name:s.current.name,initial:Object.fromEntries(IDS.map(k=>[k,s.current.initial[k]??IDLE[k]])),steps:s.current.frames.slice(0,100).map(f=>({pose:Object.fromEntries(IDS.map(k=>[k,f.target[k]??IDLE[k]])),move_s:f.move,hold_s:Math.max(0,f.duration-f.move),label:f.label}))};const res=await fetch(`/api/chat/${encodeURIComponent(user)}/simulation/plan`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session}`},body:JSON.stringify({request_id:crypto.randomUUID(),prompt,current:context}),signal:abort.signal});let payload=await res.json();if(!res.ok)throw Error(payload.error||'生成失败 / Planning failed');if(epoch!==generation||uid()!==user||token()!==session)return;if(payload.mode!=='simulation_only'||payload.hardware_executed!==false||!payload.action)throw Error('动作格式错误 / Invalid motion format');applyingPlan=true;try{s.addAction(payload.action);}finally{applyingPlan=false;}$('plan-result').textContent=`${payload.action.name}\n${payload.action.explanation}\n${payload.action.frames.length} 帧 / frames · ${payload.action.duration.toFixed(2)} s\n运行以预览 / Play to preview`;$('status').textContent='动作已生成 / Motion ready';}catch(e){if(epoch===generation)$('plan-result').textContent=e.name==='AbortError'?'请求取消或超时 / Cancelled or timed out':e.message;}finally{clearTimeout(timeout);if(epoch===generation){busy=false;abort=null;$('cancel-plan').disabled=true;connection();}}};
window.editor={loadFrame,refresh,cancel};

window.addEventListener('studio-action',()=>{if(busy&&!applyingPlan)cancel('已切换动作 / Motion changed');});

$('account-button').onclick=()=>$('account-dialog').showModal();
$('account-close').onclick=()=>$('account-dialog').close();
$('account-form').onsubmit=async e=>{e.preventDefault();const input=$('recovery-key');$('account-error').textContent='';try{const r=await fetch('/api/users/recover',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({recovery_key:input.value.trim()})});const data=await r.json();if(!r.ok||!data.user?.id||!data.session_token)throw Error('登录失败，请检查恢复链接。 / Check your recovery key.');localStorage.setItem('carrotduck_user_id',data.user.id);localStorage.setItem('carrotduck_session_token',data.session_token);input.value='';$('account-dialog').close();connection();}catch(err){$('account-error').textContent=err.message;}};
