import {IDS,IDLE,BOUNDS,makeMotion,ranges,pose} from './sim-core.mjs?v=13';
const $=x=>document.getElementById(x),s=window.studio,names={'6':'L · 6','7':'L · 7','8':'L · 8','14':'R · 14','15':'R · 15','16':'R · 16',pitch:'Head · PWM1',yaw:'Head · PWM2'};
let busy=false,abort=null,generation=0,applyingPlan=false;
for(const k of IDS){let row=document.createElement('tr');row.innerHTML=`<td>${(names[k]||'Bus · '+k)}<br><small>${k==='pitch'||k==='yaw'?'μs':'raw'}</small></td><td id="live-${k}"></td><td><input id="edit-${k}" type="number" min="${BOUNDS[k][0]}" max="${BOUNDS[k][1]}" step="1" aria-label="${(names[k]||'Bus · '+k)} target"><output id="range-${k}"></output></td>`;$('joint-rows').append(row);}
const sliders=$('servo-sliders');
function preview(){try{const p=pose(Object.fromEntries(IDS.map(k=>[k,Number($('edit-'+k).value)])));s.previewPose(p);$('status').textContent='Pose preview · Update to save';}catch(e){$('status').textContent=e.message;}}
for(const k of IDS){const label=document.createElement('label');label.className='servo-card servo-'+k;label.innerHTML=`<span>${k==='pitch'?'PWM 1':k==='yaw'?'PWM 2':'ID: '+k}</span><input type="range" min="${BOUNDS[k][0]}" max="${BOUNDS[k][1]}" step="1" id="slide-${k}" aria-label="${(names[k]||'Bus · '+k)} slider"><output id="slide-value-${k}"></output>`;sliders.append(label);$('slide-'+k).oninput=()=>{$('edit-'+k).value=$('slide-'+k).value;$('slide-value-'+k).textContent=$('slide-'+k).value;preview();};$('edit-'+k).addEventListener('input',()=>{$('slide-'+k).value=$('edit-'+k).value;$('slide-value-'+k).textContent=$('edit-'+k).value;preview();});
if(!['pitch','yaw'].includes(k)){let offset=document.createElement('span');offset.className='offset-row';offset.innerHTML=`<small>Offset</small><input id="offset-${k}" type="number" min="-125" max="125" value="0" step="1" aria-label="${(names[k]||'Bus · '+k)} preview offset" title="Model calibration offset, separate from motion targets">`;label.append(offset);$('offset-'+k).oninput=()=>{const value=Number($('offset-'+k).value);if(!s.setOffset(k,value)){$('status').textContent='Offset must be between -125 and 125';return;}$('status').textContent='Model offset · Save mapping to export';};}
}
let selected=0;
function frameTable(a){$('frames').replaceChildren();let table=document.createElement('table');table.className='frame-table';let head=document.createElement('thead');head.innerHTML='<tr><th>#</th><th>Time</th><th>Move</th>'+IDS.map(k=>`<th>${k}</th>`).join('')+'<th>Motion</th></tr>';table.append(head);let body=document.createElement('tbody');a.frames.forEach((f,i)=>{let row=document.createElement('tr');row.dataset.frame=i;for(const text of [i+1,f.start.toFixed(2),f.move.toFixed(2),...IDS.map(k=>f.target[k]??IDLE[k]),s.label(f.label)]){let cell=document.createElement('td');cell.textContent=text;row.append(cell);}row.onclick=()=>{s.seek(f.start);loadFrame(a,i);};body.append(row);});table.append(body);$('frames').append(table);$('library-count').textContent=s.library.actions.length;}
function loadFrame(a,i){selected=i;let f=a.frames[i];IDS.forEach(k=>{$('edit-'+k).value=f.target[k]??IDLE[k];$('slide-'+k).value=$('edit-'+k).value;$('slide-value-'+k).textContent=$('edit-'+k).value;});$('move-time').value=f.move;$('hold-time').value=+(f.duration-f.move).toFixed(3);document.querySelectorAll('[data-frame]').forEach(r=>r.classList.toggle('selected',Number(r.dataset.frame)===i));let r=ranges({...a,initial:{...IDLE,...a.initial},frames:a.frames.map(f=>({...f,target:{...IDLE,...f.target}}))});IDS.forEach(k=>$('range-'+k).textContent=`Range ${r[k][0]}–${r[k][1]}`);}
function refresh(){frameTable(s.current);loadFrame(s.current,0);}window.addEventListener('studio-action',refresh);refresh();
let lastIndex=-1;function update(){let state=s.state;IDS.forEach(k=>$('live-'+k).textContent=Math.round(state.pose[k]));if(state.playing){let index=s.sample(s.current,state.time).index;if(index!==lastIndex){lastIndex=index;loadFrame(s.current,index);}}requestAnimationFrame(update);}requestAnimationFrame(update);
$('time').addEventListener('input',()=>loadFrame(s.current,s.sample(s.current,s.state.time).index));
function commit(append){try{s.seek(s.state.time);const p=Object.fromEntries(IDS.map(k=>[k,Number($('edit-'+k).value)])),f={pose:p,move_s:Number($('move-time').value),hold_s:Number($('hold-time').value),label:append?'Appended pose':'Edited pose'};let steps=s.current.frames.map(v=>({pose:{...IDLE,...v.target},move_s:v.move,hold_s:Math.max(0,v.duration-v.move),label:v.label}));if(append)steps.push(f);else steps[selected]={...f,pose:{...steps[selected].pose,...f.pose}};let a=makeMotion(s.current.name+' · Edited',steps,{...IDLE,...s.current.initial});s.addAction(a);$('status').textContent='Copy saved';}catch(e){$('status').textContent=e.message;}}
$('apply-frame').onclick=()=>commit(false);$('append-frame').onclick=()=>commit(true);
$('save-motion').onclick=()=>{let blob=new Blob([JSON.stringify({schema:'xiaoji-sim-motion/v1',mode:'simulation_only',hardware_executed:false,action:s.current},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='carrot-goose-motion.json';a.click();URL.revokeObjectURL(url);};
const uid=()=> 'workbench',token=()=> 'workbench';
function connection(){$('generate').disabled=busy;$('generate').textContent=busy?'Planning…':'Generate';$('connection').textContent='';$('account-button').hidden=true;$('online-link').textContent='Project';$('online-link').href='./project.html';return !busy;}
connection();
function cancel(reason='Cancelled'){generation++;abort?.abort();abort=null;busy=false;$('cancel-plan').disabled=true;connection();$('plan-result').textContent=reason;}
$('cancel-plan').onclick=()=>cancel();$('reset').addEventListener('click',()=>{if(busy)cancel();});
$('generate').onclick=async()=>{if(!connection()){$('account-dialog').showModal();return;}const prompt=$('instruction').value.trim();if(!prompt)return;let user=uid(),session=token(),epoch=++generation;abort=new AbortController();busy=true;connection();$('cancel-plan').disabled=false;$('plan-result').textContent='Planning…';$('plan-result').scrollIntoView({block:'nearest'});$('status').textContent='Planning…';const controller=abort,started=Date.now();const progress=setInterval(()=>{if(epoch===generation){const elapsed=Math.floor((Date.now()-started)/1000);$('status').textContent=`Planning… ${elapsed}s / 45s`;$('plan-result').textContent=`Planning… ${elapsed}s / 45s`;}},1000);const timeout=setTimeout(()=>controller.abort(),45000);try{const context={name:s.current.name,initial:{...IDLE,...s.current.initial},steps:s.current.frames.slice(0,100).map(f=>({pose:Object.fromEntries(IDS.map(k=>[k,f.target[k]??IDLE[k]])),move_s:f.move,hold_s:Math.max(0,f.duration-f.move),label:f.label}))};const res=await fetch('/api/workbench/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request_id:crypto.randomUUID(),language:document.documentElement.lang==='zh-CN'?'zh':'en',prompt:prompt+'\nWrite the motion name, explanation and frame labels in '+(document.documentElement.lang==='zh-CN'?'Chinese.':'English.'),current:context}),signal:abort.signal});let payload=await res.json();if(!res.ok)throw Error(payload.error||'Planning failed');if(epoch!==generation||uid()!==user||token()!==session)return;if(payload.mode!=='simulation_only'||payload.hardware_executed!==false||!payload.action)throw Error('Invalid motion format');applyingPlan=true;try{s.addAction(payload.action);}finally{applyingPlan=false;}$('plan-result').textContent=`${payload.action.name}\n${payload.action.explanation}\n${payload.action.frames.length} frames · ${payload.action.duration.toFixed(2)} s\nPreview playing`;$('status').textContent='Preview playing';$('play').click();$('plan-result').scrollIntoView({block:'nearest'});}catch(e){if(epoch===generation){const message=e.name==='AbortError'?'Planning timed out. Please try again.':e.message;$('plan-result').textContent=message;$('status').textContent=message;$('plan-result').scrollIntoView({block:'nearest'});}}finally{clearTimeout(timeout);clearInterval(progress);if(epoch===generation){busy=false;abort=null;$('cancel-plan').disabled=true;connection();}}};
window.editor={loadFrame,refresh,cancel};

window.addEventListener('studio-action',()=>{if(busy&&!applyingPlan)cancel('Motion changed');});



const bodySelect=document.createElement('select');bodySelect.id='body-controls';bodySelect.setAttribute('aria-label','Joint controls');bodySelect.innerHTML='<option value=upper>Head and arms</option><option value=lower>Legs</option>';document.querySelector('.viewportbar').append(bodySelect);function bodyCards(){for(const k of IDS){const leg=!['6','7','8','14','15','16','pitch','yaw'].includes(k);document.querySelector('.servo-'+k).hidden=leg!==(bodySelect.value==='lower');}}bodySelect.onchange=bodyCards;bodyCards();
