import * as T from 'three';
import {createRobot} from './robot.js?v=6';
import {OrbitControls} from './vendor/OrbitControls.js';
const labels={"复原到起点 · 安静待机": "Rest", "你靠近 · 转向你": "Turn toward you", "手指向左 · 双手安静": "Look at finger", "手指向右": "Look right", "手指向上": "Look up", "手指向下": "Look down", "手停 · 视线停在手上": "Hold gaze", "看向你的脸": "Look at face", "再看看你的手": "Look at hand", "又看向你": "Look at face", "再看手 · 低头等你": "Look down and wait", "你的第一句文字": "First question", "不告诉你 · 文字先出现": "Wait for reply", "轻轻点头 · 低下": "Nod", "点头以后 · 抬头看你": "Look up at you", "让开心停留一下": "Pause", "Cheer · 双臂前抬与点头摇摆 · 1/5": "Cheer", "Cheer · 双臂前抬与点头摇摆 · 2/5": "Cheer", "Cheer · 双臂前抬与点头摇摆 · 3/5": "Cheer", "Cheer · 双臂前抬与点头摇摆 · 4/5": "Cheer", "Cheer · 双臂前抬与点头摇摆 · 5/5": "Cheer", "再看你 · 等你的手移开": "Look at hand", "手指已移开 · 注意到离开": "Hand withdraws", "第一次轻轻抬手": "Raise arm", "犹豫 · 缩回一点": "Hesitate", "Hey · 看向你的脸": "Hey, look at face", "再看你的手 · 决定邀请": "Look at hand", "第二次邀请 · 胸前停住": "Invite again", "坚定地等你 · 看手再看脸": "Nod and look back", "你的第二句文字": "Second question", "拥抱回复出现 · 保持邀请": "Read hug reply", "双臂向前 · 邀请拥抱 · 1/3": "Offer hug", "双臂向前 · 邀请拥抱 · 2/3": "Offer hug", "双臂向前 · 邀请拥抱 · 3/3": "Offer hug", "一个不接触的拥抱 · 停留": "Hold invitation", "自然放下双臂": "Lower arms", "拥抱后看向你 · 回到待机": "Return to rest"};
const label=x=>labels[x]||x;
const $=id=>document.getElementById(id);
const library=await (await fetch('./library.json')).json(), mapping=structuredClone(library.mapping);
const scene=new T.Scene();scene.background=new T.Color('#fffaf5');
const camera=new T.PerspectiveCamera(34,1,.01,20);camera.position.set(0,.31,1.15);
const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.setClearColor('#fffaf5');$('view').prepend(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.24,0);controls.enableDamping=true;controls.minDistance=.5;controls.maxDistance=2.2;controls.maxPolarAngle=Math.PI*.49;
scene.add(new T.HemisphereLight(0xffffff,0xc4c8cd,2.0));const light=new T.DirectionalLight(0xffffff,2.0);light.position.set(.6,1,1);light.castShadow=true;light.shadow.mapSize.set(2048,2048);light.shadow.camera.left=-.8;light.shadow.camera.right=.8;light.shadow.camera.top=.8;light.shadow.camera.bottom=-.8;light.shadow.normalBias=.002;scene.add(light);
const {root:robot,joints}=createRobot(scene);
const material=c=>new T.MeshStandardMaterial({color:c,roughness:.85});
const floor=new T.Mesh(new T.PlaneGeometry(20,20),material('#f4ece3'));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);
const grid=new T.GridHelper(1.5,30,0xccb49e,0xe4d5c6);grid.position.y=.001;scene.add(grid);
const resize=new ResizeObserver(()=>{const w=$('view').clientWidth,h=$('view').clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();});resize.observe($('view'));
let current=library.actions[0],time=0,playing=false,last=performance.now(),lastFrame=-1,audioInstance=null,run=crypto.randomUUID(),sequence=0,seen=new Set();
let log=[];const note=(status,extra={})=>{log.push({schema:'duck-sim-playback/v1',mode:'simulation_only',hardware_executed:false,simulation_run_id:run,status,...extra});};
function stopAudio(){if(audioInstance){audioInstance.pause();audioInstance=null;}}
function choose(a){stopAudio();if(playing)note('cancelled');current=a;time=0;playing=false;lastFrame=-1;$('play').textContent='Play';$('time').max=a.duration;$('evidence').textContent=`${a.frames.length} frames · ${a.duration.toFixed(2)} s`;$('source').textContent=(a.source||'').includes('d6a')?'TonyPi / .d6a':'Carrot Goose / Motion library';$('frames').replaceChildren();a.frames.forEach((f,i)=>{let b=document.createElement('button');b.textContent=`${String(i+1).padStart(2,'0')}  ${f.label}`;b.onclick=()=>seek(f.start);$('frames').append(b);});drawPose();window.dispatchEvent(new Event('studio-action'));}
function seek(t){time=Math.min(current.duration,Math.max(0,t));playing=false;stopAudio();lastFrame=-1;$('play').textContent='Play';drawPose();}
function sample(a,t){let index=a.frames.findIndex(f=>t<f.start+f.duration);if(index<0)index=a.frames.length-1;const f=a.frames[index],u=f.move===0?1:Math.max(0,Math.min(1,(t-f.start)/f.move));let pose={};for(const k of Object.keys(f.target))pose[k]=f.from[k]+(f.target[k]-f.from[k])*u;return {pose,f,index};}
function drawPose(){const {pose,f,index}=sample(current,time);for(const [id,g]of Object.entries(joints)){const m=mapping[id];g.rotation.set(0,0,0);g.rotation[m.axis]=T.MathUtils.degToRad((pose[id]-m.neutral)*m.degrees_per_unit*m.sign);if(id==='7')g.rotation.z+=.1;if(id==='15')g.rotation.z-=.1;}
  $('beat').textContent=label(f.label);$('clock').textContent=`${time.toFixed(2)} / ${current.duration.toFixed(2)} s`;$('phase').textContent=`${index+1} / ${current.frames.length} · ${playing?'Playing':time>=current.duration?'Complete':'Ready'}`;$('time').value=time;
  $('dialogue').textContent=f.utterance?`“${f.utterance}”`:f.gate==='happy_reply'?'You: Are you happy today?\nDuck: Not telling.':f.gate==='hug_reply'?"You: What is it?\nDuck: Just wanted to give you a hug.":'';
  for(const id of Object.keys(joints))$('v_'+id).textContent=Math.round(pose[id]);$('raw').textContent=JSON.stringify(Object.fromEntries(Object.entries(pose).map(([k,v])=>[k,Math.round(v)])),null,1);
  if(index!==lastFrame&&playing){note('frame_started',{action:current.name,index});if(f.utterance&&$('audio').checked){stopAudio();audioInstance=new Audio(f.utterance.startsWith('Mm')?'./audio/mm.wav':'./audio/hey.wav');audioInstance.play().catch(()=>{$('status').textContent='Audio unavailable. Continue with audio off.';});}}
  lastFrame=index;
}
for(const id of Object.keys(joints)){let v=document.createElement('div');v.className='value';v.innerHTML=`<small>${id==='pitch'?'PWM1 · Pitch µs':id==='yaw'?'PWM2 · Yaw µs':'BUS '+id+' · raw'}</small><b id="v_${id}"></b>`;$('values').append(v);let op=new Option(id,id);$('joint').add(op);}
function options(){let selected=current.name;$('action').replaceChildren();library.actions.filter(a=>(a.name+' '+(window.gooseLocale?.translate(a.name)||'')).toLowerCase().includes($('search').value.toLowerCase())).forEach(a=>$('action').add(new Option(a.name,a.name)));$('action').value=selected;}
$('search').oninput=options;$('action').onchange=()=>choose(library.actions.find(a=>a.name===$('action').value));
$('play').onclick=()=>{if(time>=current.duration)time=0;playing=!playing;if(!playing)stopAudio();else {lastFrame=-1;note('started',{action:current.name});}last=performance.now();$('play').textContent=playing?'Pause':'Play';};
$('reset').onclick=()=>{note('cancelled');run=crypto.randomUUID();sequence=0;seen.clear();seek(0);};$('time').oninput=()=>seek(Number($('time').value));
$('front').onclick=()=>{camera.position.set(0,.31,1.15);controls.target.set(0,.24,0);};$('perspective').onclick=()=>{camera.position.set(.51,.36,1.05);controls.target.set(0,.24,0);};$('side').onclick=()=>{camera.position.set(.95,.34,.22);controls.target.set(0,.24,0);};
function updateMappingControls(){const m=mapping[$('joint').value];$('axis').value=m.axis;$('sign').value=m.sign;} $('joint').onchange=updateMappingControls;for(const id of ['axis','sign'])$(id).onchange=()=>{const m=mapping[$('joint').value];m.axis=$('axis').value;m.sign=Number($('sign').value);drawPose();};
$('export').onclick=()=>{let a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(mapping,null,2)],{type:'application/json'}));a.href=url;a.download='carrot-goose-mapping.json';a.click();URL.revokeObjectURL(url);};
function acceptEvent(e){if(e.schema!=='duck-sim-event/v1'||e.mode!=='simulation_only'||e.surface!=='tonypi_3d_simulator'||e.hardware_executed!==false)throw Error('Only simulation events are accepted');if(e.simulation_run_id!==run||typeof e.event_id!=='string'||!e.event_id||seen.has(e.event_id)||e.sequence!==sequence+1||!Number.isFinite(e.expires_at)||e.expires_at<=Date.now()||e.final!==true||!['scripted','llm','operator'].includes(e.source_kind))throw Error('Invalid event: expired, repeated, out of order or mismatched run');let target={'wave':'wave!!','happy':'happy_greeting_low','hug':'hug final.d6a'}[e.cue];let a=library.actions.find(a=>a.name===target);if(!a)throw Error('Unsupported motion');seen.add(e.event_id);sequence=e.sequence;choose(a);$('action').value=a.name;playing=true;last=performance.now();lastFrame=-1;$('play').textContent='Pause';$('status').textContent=`Simulation event received · ${e.source_kind} · ${e.cue}`;note('started',{event_id:e.event_id,action:a.name});return true;}
$('example').onclick=()=>{$('event').value=JSON.stringify({schema:'duck-sim-event/v1',mode:'simulation_only',surface:'tonypi_3d_simulator',hardware_executed:false,simulation_run_id:run,event_id:crypto.randomUUID(),sequence:sequence+1,source_kind:'scripted',cue:'wave',final:true,expires_at:Date.now()+120000},null,2);};$('accept').onclick=()=>{try{acceptEvent(JSON.parse($('event').value));$('error').textContent='';}catch(e){$('error').textContent=e.message;}};
document.addEventListener('visibilitychange',()=>{if(document.hidden){playing=false;stopAudio();$('play').textContent='Play';note('cancelled',{reason:'page_hidden'});}});
options();choose(current);updateMappingControls();
window.studio={label,library,sample,seek,choose,acceptEvent,get current(){return current},addAction(a){library.actions.push(a);$('search').value='';choose(a);options();},get state(){return {time,playing,action:current.name,run,sequence,log,pose:sample(current,time).pose}},renderer,scene};
function tick(now){const dt=Math.min(.1,(now-last)/1000);last=now;if(playing){time=Math.min(current.duration,time+dt*Number($('speed').value));drawPose();if(time>=current.duration){playing=false;stopAudio();$('play').textContent='Play';note('completed',{action:current.name});drawPose();}}controls.update();renderer.render(scene,camera);requestAnimationFrame(tick);}requestAnimationFrame(tick);

await import('./editor.js?v=6');
await import('./locale.js?v=6');

